package org.example.department.enums;

public enum CourseTitle {
    MATHEMATICS, ENGLISH_LANG, BASIC_STUDIES, PHYSICS,
    CHEMISTRY, BIOLOGY, AGRIC_SCIENCE, LIT_ENGLISH, COMPUTER_STUDIES,
    GOVERNMENT, ECONOMICS, ACCOUNTING, LIT_IN_ENGLISH
}
